---

- name: intall apapche on Debian
  apt:
    name: apache2
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: set up service on Debian
  service:
    name: apache2
    state: started
    enabled: true
  when: ansible_os_family == 'Debian'

- name: install and set up apache on Windows
  include_tasks:
    file: install_apache_Windows.yml
  when: ansible_os_family == 'Windows'

- name: config ports on Debian
  include_tasks:
    file: config_ports_Debian.yml
  when: ansible_os_family == 'Debian'

- name: config ports on Windows
  include_tasks:
    file: config_ports_Windows.yml
  when: ansible_os_family == 'Windows'
  
- name: generate weather html page for Debian
  template:
    src: weather.html.j2
    dest: '/var/www/html/index.html'
    mode: '0644'
  when: ansible_os_family == 'Debian'
  notify:
    - restart apache on Debian

- name: generate weather html page for Windows
  template:
    src: weather.html.j2
    dest: 'C:\\Apache24\\htdocs\\index.html'
  when: ansible_os_family == 'Windows'
  notify:
    - restart apache on Windows